import type { Metadata } from 'next';
import { AuthProvider } from '@/hooks/use-auth';
import { Sidebar, SidebarContent, SidebarProvider } from '@/components/ui/sidebar';
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { auth } from '@/lib/firebase';
import { onAuthStateChanged, User } from 'firebase/auth';

export const metadata: Metadata = {

  title: 'InvoiceFlow',
  description: 'Generated by Firebase Studio',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user: User | null = await new Promise((resolve) => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      unsubscribe();
      resolve(user);
    });
  });

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SidebarProvider>
            <div className="flex h-screen">
              <Sidebar className="w-64 border-r flex-shrink-0">
                <SidebarContent>
                  <div className="p-4 flex items-center space-x-2">
                    <Avatar className="h-8 w-8">
                      {user?.photoURL && user ? (
                        <AvatarImage src={user.photoURL} alt={user ? (user.displayName || "User Avatar") : "User Avatar"} />
                      ) : (
                        <AvatarFallback>{user ? (user.displayName?.substring(0, 2).toUpperCase() || 'CN') : 'CN'}</AvatarFallback>
                      )}
                    </Avatar>
                    <span className="font-semibold">InvoiceFlow</span>
                  </div>
                  {children}
                </SidebarContent>
              </Sidebar>
            </div>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
